vim.keymap.set("n", "<leader>o", vim.cmd.Exp)
vim.keymap.set("n", "<leader>rn", function()
  return ":IncRename " .. vim.fn.expand("<cword>")
end, { expr = true })
vim.keymap.set('n', '<leader>r', ':so $MYVIMRC<CR><Esc>')
vim.keymap.set('v', "<leader>y", '\"+y')
vim.keymap.set('n', '<leader>t', '<Esc>:tabnew<CR>')
vim.keymap.set('n', '<leader>n', '<Esc>:tabnext<CR>')
vim.keymap.set('n', '<leader>b', '<Esc>:tabprev<CR>')

