vim.keymap.set("n", "<leader>o", vim.cmd.Exp)
vim.keymap.set("n", "<leader>rn", function()
  return ":IncRename " .. vim.fn.expand("<cword>")
end, { expr = true })
vim.keymap.set('n', '<leader>r', ':so $MYVIMRC<CR>')
vim.keymap.set("v", "<leader>y", '\"+y')
